version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: 0
      BUNDLE_PATH: /usr/local/bundle
      BUNDLE_WITHOUT: ""
      NODE_ENV: development
      MUNICIPE_CRUD_DATABASE_PASSWORD: example
      SMTP_ADDRESS: smtp.example.com
      SMTP_PORT: 587
      SMTP_DOMAIN: example.com
      SMTP_USERNAME: username
      SMTP_PASSWORD: password
      SENDPULSE_API_USER: username
      SENDPULSE_API_KEY: password

    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: municipe_crud
      POSTGRES_PASSWORD: example
      POSTGRES_DB: municipe_crud_development